---

- hosts: centos7-lemp
  user: ansi

  tasks:
    - name: copy MAIN nginx config
      ansible.builtin.copy:
      src: /opt/docker/lemp2/ansible/nginx/nginx.conf
      dest: /opt/docker/lemp2/nginx/nginx.conf
      owner: nginx
      group: nginx
      backup: yes
      become: yes

  tasks:
    - name: restart web_srv container
      docker_container:
        name: web_srv
        image: nginx:alpine
        state: started
        restart: yes
        become: yes
