version: '3'
services:

 memcached1:
   image: "memcached:1.6-alpine"
   container_name: mem_srv_1
   restart: always
   ports:
    - "127.0.0.1:11211:11211"
   command:                                                                                                                                                                                          
    - '-m 100'                                                                                                                                                                                      
    - '-p 11211'
   deploy:
     resources:
       limits:
         cpus: 0.05
         memory: 50m
    
 memcached2:
   image: "memcached:1.6-alpine"
   container_name: mem_srv_2
   restart: always
   ports:
    - "127.0.0.1:11222:11222"
   command:                                                                                                                                                                                          
    - '-m 100'                                                                                                                                                                                      
    - '-p 11222'
   deploy:
     resources:
       limits:
         cpus: 0.05
         memory: 50m

 memcached3:
   image: "memcached:1.6-alpine"
   container_name: mem_srv_3
   restart: always
   ports:
    - "127.0.0.1:11233:11233"
   command:                                                                                                                                                                                          
    - '-m 100'                                                                                                                                                                                      
    - '-p 11233'
   deploy:
     resources:
       limits:
         cpus: 0.05
         memory: 50m
    
 memcached4:
   image: "memcached:1.6-alpine"
   container_name: mem_srv_4
   restart: always
   ports:
    - "127.0.0.1:11244:11244"
   command:                                                                                                                                                                                          
    - '-m 100'                                                                                                                                                                                      
    - '-p 11244'
   deploy:
     resources:
       limits:
         cpus: 0.05
         memory: 50m

 database_srv:
  image: "mariadb:10.5"
  container_name: database_srv
  restart: always
  ports:
   - "127.0.0.1:3306:3306"
  environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  volumes:
   - /opt/docker/lemp2/mysql/DB:/var/lib/mysql
   - /opt/docker/lemp2/mysql/conf:/etc/mysql
   - /opt/docker/lemp2/mysql/log:/var/log/mysql
   deploy:
     resources:
       limits:
         cpus: 0.25
         memory: 500m

 php_srv:
  image: "php:7.4-fpm-alpine"
  container_name: php_srv
  restart: always
  volumes:
   - /opt/docker/lemp2/nginx/www:/var/www
   - /opt/docker/lemp2/php-fpm:/etc/php/7.4/fpm/pool.d/
   - /opt/docker/lemp2/php-fpm/php.ini-production:/usr/local/etc/php/php.ini
  ports:
   - "127.0.0.1:9000:9000"
   deploy:
     resources:
       limits:
         cpus: 0.25
         memory: 450m

 haproxy:
  image: "haproxy:2.3-alpine"
  container_name: haproxy_srv
  restart: always
  ports:
   - 8080:80
   - 8081:443
  volumes:
   - /opt/docker/lemp2/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
   - /opt/docker/lemp2/haproxy/test-site.pem:/etc/ssl/certs/test-site.pem
   - /opt/docker/lemp2/haproxy/whitelist.lst:/usr/local/etc/haproxy/whitelist.lst
  depends_on:
    - web_srv
   deploy:
     resources:
       limits:
         cpus: 0.10
         memory: 150m

 web_srv:
  image: "nginx:alpine"
  container_name: web_srv
  restart: always
  volumes:
   - /opt/docker/lemp2/nginx/vhost:/etc/nginx/conf.d/
   - /opt/docker/lemp2/nginx/www:/var/www/
   - /opt/docker/lemp2/nginx/logs:/var/log/nginx/
   - /opt/docker/lemp2/nginx/cert:/etc/nginx/cert/
   - /opt/docker/lemp2/nginx/nginx.conf:/etc/nginx/nginx.conf
  ports:
   - "127.0.0.1:80:80"
   - "127.0.0.1:443:443"
  depends_on:
    - php_srv

  deploy:
    resources:
      limits:
        cpus: 0.20
        memory: 200m
