version: '3'
services:

 database_srv:
  image: "mariadb:latest"
  container_name: database_srv
  restart: always
  ports:
   - "3306:3306"
  environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  volumes:
   - ./mysql/DB:/var/lib/mysql
   - ./mysql/conf:/etc/mysql

 php_srv:
  image: "php:7.4-fpm-alpine"
  container_name: php_srv
  restart: always
  volumes:
   - ./nginx/www:/var/www
   - ./php-fpm:/etc/php/7.4/fpm/pool.d/
  ports:
   - "9000:9000" 

 haproxy:
  image: "haproxy:2.3-alpine"
  container_name: haproxy_srv
  restart: always
  ports:
   - 8080:80
   - 8081:443
  volumes:
   - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
   - ./haproxy/test-site.pem:/etc/ssl/certs/test-site.pem
  depends_on:
    - web_srv

 web_srv:
  image: "nginx:alpine"
  container_name: web_srv
  restart: always
  volumes:
   - ./nginx/vhost:/etc/nginx/conf.d/
   - ./nginx/www:/var/www/
   - ./nginx/logs:/var/log/nginx/
   - ./nginx/cert:/etc/nginx/cert/
  ports:
   - "80:80"
   - "443:443"
  depends_on:
    - php_srv

 memcached:
   image: "memcached:alpine"
   container_name: mem_srv
   restart: always
   ports:
    - "11211:11211"
      
