version: '3'
services:

 web_srv:
  image: "nginx:latest"
  container_name: web_srv
  restart: unless-stopped
  volumes:
   - ./nginx/vhosts:/etc/nginx/conf.d/
   - ./nginx/www:/var/www/
   - ./nginx/logs:/var/log/nginx/
   - ./nginx/cert:/etc/nginx/conf.d/
  ports:
   - "80:80"
   - "443:443"

 database_srv:
  image: "mariadb:latest"
  container_name: database_srv
  restart: unless-stopped
  ports:
   - "3306:3306"
  environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSSWORD}
  volumes:
    - ./mysql:/var/lib/mysql
    - ./mysql:/etc/mysql

  php_srv:
   image: "php:7.5-fpm"
   container_name: php_srv
   volumes:
    - ./nginx/www:/var/www
    - ./php-fpm:/etc/php/7.5/fpm/pool.d/
   ports:
    - "9000:9000"       

  memcached:
    image: "memcached:latest"
    container_name: mem_srv
    restart: unless-stopped
    ports:
      - "11211:11211"
      
  haproxy:
    image: "haproxy:2.4"
    container_name: haproxy_srv
    ports:
      - 8080:80
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy/cert.pem:/etc/ssl/certs/test-site.pem
