
---

- hosts: {{ master_srv }}
  user: ansi
  vars_files:
    - vars/default.yml
    
   tasks:
    - name: DUMP databases to VOLUME !!!
      community.mysql.mysql_db: login_user=root login_password={{ DB_ROOT_PASSWORD }} 
         state: dump
         name:
           - testbase
         target: /opt/docker/lemp2/mysql/DB/dump-testbase.sql
      become: yes
