---

- hosts: centos7-lemp
  vars_files:
    - vars/default.yml

  tasks:
    - name: copy maria master config
      ansible.builtin.copy:
      src: /opt/docker/lemp2/ansible/maria/master-my.cnf
      dest: /opt/docker/lemp2/mysql/conf/my.cnf
      owner: mysql
      group: mysql
      backup: yes

  tasks:
    - name: restart mariaDB container
      docker_container:
        name: database_srv
        image: mariadb:10.5
        state: started
        restart: yes

- hosts:  <database_srv or IP container>
  tasks:
    - name: Create database user with name 'master' and password (look VARS) with replication privileges
      community.mysql.mysql_user: login_user=root login_password={{ DB_ROOT_PASSWORD }} 
        name: master
        password: {{ master_password }}
        priv: '*.*:REPLICATION SLAVE,REPLICATION CLIENT'
        state: present
        
