---

- hosts: {{ ip_db }}
  vars_files:
    - vars/default.yml
    
   tasks:
    - name: Create database user with name 'master' and password (look VARS) with replication privileges
      community.mysql.mysql_user: login_user=root login_password={{ DB_ROOT_PASSWORD }} 
        name: master
        password: {{ master_password }}
        priv: '*.*:REPLICATION SLAVE,REPLICATION CLIENT'
        state: present
        
        
    - name: Get master binlog file name and binlog position AND returt value to slave_srv !!!  
      community.mysql.mysql_replication: login_user=root login_password={{ DB_ROOT_PASSWORD }} 
         login_host: {{ master_srv }}
         mode: getmaster
         delegate_to: {{ master_srv }}
         register: master
         
    - name: Stop slave 
      community.mysql.mysql_replication: login_user=root login_password={{ DB_ROOT_PASSWORD }} 
        login_host: {{ slave_srv }}
        mode: stopslave
        
    - name: Change master to master server (master_srv) and use binary log mysql with position
      community.mysql.mysql_replication: login_user=master login_password={{ master_password }} 
        login_host: {{ slave_srv }}
        mode: changemaster
        master_host: {{ master_srv }}
        master_log_file: {{ master.File }}
        master_log_pos: {{ master.Position }}
        
    - name: Start slave
      community.mysql.mysql_replication: login_user=root login_password={{ DB_ROOT_PASSWORD }} 
      login_host: {{ slave_srv }}
      
      
      
        mode: startslave
