---

- hosts: centos7-lemp
  user: ansi
  vars_files:
    - vars/default.yml

  tasks:
    - name: copy maria slave config
      ansible.builtin.copy:
      src: /opt/docker/lemp2/ansible/maria/slave-my.cnf
      dest: /opt/docker/lemp2/mysql/conf/my.cnf
      owner: mysql
      group: mysql
      backup: yes
      become: yes

  tasks:
    - name: restart mariaDB container
      docker_container:
        name: database_srv
        image: mariadb:10.5
        state: started
        restart: yes
      become: yes
        
