
---

- hosts: client_ip

  tasks:
     - name: connect to remote srv
       ansible.builtin.ssh: host=1.1.1.1 port=22 remote_user=root private_key_file=/opt/docker/lemp2/ansible/tunnel/id.rsa ssh_extra_args='-w any'
       tags:
         - con_to_srv
  
  tasks:
    - name: Configure IP address 10.10.10.2/32 on tun0
      community.network.ipadm_addr: addr=10.10.10.2/32 addrobj=tun0/v4 ip_tunnel_remote=10.10.10.10  ip_tunnel_dev=tun0 state=present
      tags:
        - tun_conf

  tasks:      
    - name: add static route
      net_static_route:
        prefix: 192.168.1.0
        mask: 255.255.255.0
        next_hop: 10.10.10.10
      tags:
        - add_route
