
---

- hosts: ssh-srv

    
  tasks:    
    - name: auth sshd  
    - lineinfile: dest=/etc/ssh/sshd_config regexp='^#?PermitTunnel' line='PermitTunnel yes'
    - lineinfile: dest=/etc/ssh/sshd_config regexp='^#?PermitRootLogin' line='PermitRootLogin yes'
      tags:
        - sshd_conf
    
  tasks:    
    - name: restart sshd
      service:
        name: sshd
        state: restarted
      tags:
        - sshd_restart
   
  tasks:   
    - sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
      tags:
        -  sysctl_reload
    
  tasks:
    - name: Configure IP address 10.10.10.10/32 on tun0
      community.network.ipadm_addr: addr=10.10.10.10/32 addrobj=tun0/v4 ip_tunnel_remote=10.10.10.2  ip_tunnel_dev=tun0 state=present
      tags:
        - tun_conf
