---

- hosts: centos7-lemp
  tasks:
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
 
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest

  tasks:
    - name: Install soft
      yum: name={{ item }} state=latest
      with_items:
        - yum-utils
        - lvm2
        - device-mapper-persistent-data
        - docker-ce
        - git
  
    - service:
      name: Enable services
      service: name={{ item }} state=started enabled=yes
      with_items: 
        - docker

    - name: install docker-compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose;chmod +x /usr/bin/docker-compose
      args:
        executable: /usr/bin/bash

    - name: clone docker file from github
      git:
         repo: "https://github.com/reeves0x0/lemp2.git"
         dest: /opt/docker/
         version: master
		 
    - name: start docker-compose file
      docker_compose:
        project_src: /opt/docker/lemp2
        files:
        - docker-compose.yml
