FROM php:7.4-fpm-alpine

WORKDIR /var/www

# requa
RUN apk update && apk add --no-cache \
    autoconf \
    automake \
    gcc \
    make \
    g++ \
    zlib-dev \
    libtool \
    freetype \
    libjpeg-turbo \
    libpng \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    freetype-dev \
    icu-dev \
    libxml2-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libzip-dev \
    libmemcached \
    libmemcached-dev \
    geoip\
    geoip-dev \
    php7-mcrypt \
    php7-common \
    php7-pear \
  && rm -rf /tmp/*

#show precompiled module     docker run --rm php:7.4-fpm-alpine php -m
RUN docker-php-ext-install  bcmath intl opcache  soap gd zip
RUN pecl install geoip \
    && pecl install memcached \
    && pecl install redis \
    && pecl install igbinary \
    && docker-php-ext-enable redis geoip memcached igbinary
